import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "e-commerce app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MainLayout>
            <GlobalStyle />
            {children}
          </MainLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
